name: QA
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]
jobs:
  tests:
    name: Dt0 QA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, dom, fileinfo, gmp, bcmath
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ hashFiles('**/composer.json') }}
          restore-keys: composer-

      - name: Remove composer.lock
        run: rm -f composer.lock

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check code style
        run: vendor/bin/pint --ansi --config pint.json --test

      - name: PHPStan src
        run: composer stan

      - name: PHPStan tests
        run: composer stan-tests

      - name: Compute Coverage
        run: vendor/bin/phpunit --colors --coverage-clover ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
